### PR TITLE
Implemented Dark and Light Mode Toggle

### LINKED ISSUE #24: Implement dark and light mode toggle
Currently the website is only using light mode.

Requirements:
- [ ] Create a toggle button in the navbar just next to github icon
- [ ] The toggle button itself should change to black on light and vice versa
- [ ] Toggle button should change the entire website to dark if light or vice versa

Currently:
image

Expected:
image

Take the toggle icon from:
https://www.svgrepo.com/svg/348420/night-mode

### PR DESCRIPTION
**Pull request by richmondnkrumah**
Implementation of dark mode and Light mode
Fixes #24 
**Before Implementation**

Screenshot_2023-10-20_22_37_07
**After Implementation**

Screenshot_2023-10-20_22_36_57

### CODE REVIEW

**Comment by devsargam** [comment]
@Arkhein6 that was quick. Thanks

**Review by devsargam — CHANGES_REQUESTED** [review]
Few takes on this:
- For dark mode the cards should also be gray
- Also the logo should be while like the github icon
- Also the search bar can be improved to something like
image

Can you work on these? @Arkhein6

**Comment by richmondnkrumah** [comment]
Sure. I will start working on it.

**Comment by richmondnkrumah** [comment]
Hey, I made the proposed changes. Review and then give me updates.

**Review by devsargam — APPROVED** [review]
LGTM!

**Comment by devsargam** [comment]
Only thing that's concerning me is the mobile view. I'll think of a workaround for that.

**Comment by devsargam** [comment]
Thanks @Arkhein6.

**Pull request merged**
