### PR TITLE
Added ipwhois api for geolocation tracing of API. 

### PR DESCRIPTION
**Pull request by Insomniac2904**
API DOCS: [ipwhosis.io](https://ipwhois.io/documentation)

### CODE REVIEW

**Comment by Insomniac2904** [comment]
In case of any problem please tag me in comments @Pawan2061 @devsargam

**Comment by devsargam** [comment]
@Insomniac2904 for some reason the image is not showing up. Can you please check that?

**Comment by Insomniac2904** [comment]
@devsargam Fixed It !!

**Comment by devsargam** [comment]
@Insomniac2904 nice job.

**Pull request merged**
